server:
  port: 9090
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zhou?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
